language: node_js

node_js:
 - "11.8.0"

 services:
  - postgresql
  env:
   - DB=postgres
  global:
  - PGPORT=5433

cache:
directories:
  - "node_modules"

script:
  - npm run test

after_script:
  - npm run coverage
